#!/bin/bash

# Rodando PHP-CS-Fixer
output=$(docker compose exec app ./vendor/bin/pint)

phpstan_output=$(docker compose exec app ./vendor/bin/phpstan analyse)
# Rodando PHPStan e garantindo saída em formato JSON
phpstan_erro=$(docker compose exec app ./vendor/bin/phpstan analyse --error-format=json)

# Exibindo a saída do PHPStan
echo "$phpstan_output"

# Verificando erros do PHPStan
error_count=$(echo "$phpstan_erro" | jq '.files | to_entries | map(select(.value.errors > 0)) | length')
echo "$error_count"
if [[ $error_count -gt 0 ]]; then
  echo "Erro(s) encontrado(s) pelo PHPStan. Corrija os erros antes de continuar."
  exit 1
fi

# Verificando se o arquivo phpstan.neon existe
if [ -f "./phpstan.neon" ]; then
  # Caso o arquivo phpstan.dist.neon exista, restaura a lista de arquivos ignorados
  sed -i 's/#.*-.*phpstan-baseline.neon/\t- .*phpstan-baseline.neon/' phpstan.neon
else
  echo "Arquivo phpstan.neon não encontrado. Ignorando restauração de lista de arquivos."
fi

exit 0
